### ISSUE TITLE
Use glob for matching files

### ISSUE THREAD

**Issue by evilebottnawi** [evanshortiss/lintspaces-cli#10]

**Comment by evanshortiss** [comment]
Hey @evilebottnawi can you provide an example of what you expect?

Also, it's possible to use the find command do this as an alternative:

_lintspaces -s 2 $(find ./ -name *.thing.js)_

**Comment by evilebottnawi** [comment]
@evanshortiss testing on window and other system

**Comment by evanshortiss** [comment]
OK, keep me posted @evilebottnawi

**Comment by evanshortiss** [comment]
@evilebottnawi how did this solution work for you?

**Comment by evanshortiss** [comment]
@evilebottnawi closing this. Let me know if there's still a feature required.
