### ISSUE TITLE
verbose option

### ISSUE THREAD

**Issue by gemal** [evanshortiss/lintspaces-cli#12]
could be nice with a verbose option that printed out:
```
- checking file /var/tmp/xxx.js
- checking file /var/tmp/xxx2.js
```

**Comment by evanshortiss** [comment]
@gemal agreed, this could be useful. So you would like output like this?

```
~/workspaces/express-expeditious$ lintspaces -s 4 -d "tabs" lib/cache-key.js 

Checking: /workspaces/express-expeditious/lib/cache-key.js

File: /workspaces/express-expeditious/lib/cache-key.js
Line: 5 Unexpected spaces found. [warning]
Line: 6 Unexpected spaces found. [warning]
Line: 7 Unexpected spaces found. [warning]
Line: 8 Unexpected spaces found. [warning]
Line: 9 Unexpected spaces found. [warning]
Line: 10 Unexpected spaces found. [warning]
Line: 11 Unexpected spaces found. [warning]
Line: 12 Unexpected spaces found. [warning]
Line: 13 Unexpected spaces found. [warning]
Line: 14 Unexpected spaces found. [warning]
Line: 15 Unexpected spaces found. [warning]
Line: 16 Unexpected spaces found. [warning]

```

I'd be happy to accept a PR for this if you have something in the works. If not I can try get around to it sometime 👍

**Comment by gemal** [comment]
tried to add a pull request
Also fixing some inconsistency in the "." of the sentences

**Comment by evanshortiss** [comment]
Sounds good @gemal, I'll keep an eye out and review it once you have opened the PR. Appreciate it!

**Comment by gemal** [comment]
the pull requests is there

**Comment by evanshortiss** [comment]
@gemal I can't see it here: https://github.com/evanshortiss/lintspaces-cli/pulls

Could you open it again?

**Comment by gemal** [comment]
should be there now. Not a github expert :)

**Comment by gemal** [comment]
pull is there with a fix to the readme too

**Comment by gemal** [comment]
@evanshortiss can you review and merge?

**Comment by evanshortiss** [comment]
@gemal added comments to the PR, very quick fixes 😄
