### ISSUE TITLE
Deep search like **/*.txt does not work

### ISSUE THREAD

**Issue by jantimon** [evanshortiss/lintspaces-cli#16]
Are you open for a pull request to fix this?

I would suggest to use https://www.npmjs.com/package/glob

**Comment by evanshortiss** [comment]
@jantimon typically I've just used this module like so `lintspaces -s 2 -d spaces $(find ./lib -name *.js)`, but if you'd like globbing support I'm open to it 👍

**Comment by jantimon** [comment]
Cool we got some windows users in the team so I guess it would help

**Comment by jantimon** [comment]
@evanshortiss do you have time to give me feedback on #17?

**Comment by evanshortiss** [comment]
Added quick comment about a potential regression
