### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by gemal** [evanshortiss/lintspaces-cli#24]
low             Prototype Pollution
  Package         deep-extend
  Dependency of   lintspaces-cli [dev]
  Path            lintspaces-cli > lintspaces > rc > deep-extend
  More info       https://nodesecurity.io/advisories/612

**Comment by evanshortiss** [comment]
@gemal looks like it's being addressed here https://github.com/schorfES/node-lintspaces/pull/45

Will leave this open so we can determine if this module needs to bump the underlying lintspaces it uses.

**Comment by schorfES** [comment]
Hallo @gemal,

I've updated all dependencies to resolve all of those security vulnerabilities related to deep-extend and hoek. The current release 0.6.2 will fix this.

**Comment by evanshortiss** [comment]
Thanks @schorfES I'll need to update the package.json to use 0.6.x

**Comment by evanshortiss** [comment]
@gemal addressed in 0.6.1 of lintspaces-cli which is now on npm
