### ISSUE TITLE
Provide machine-parseable (JSON) output

### ISSUE THREAD

**Issue by mwgamble** [evanshortiss/lintspaces-cli#28]
It would be great if this tool could have an option to provide its output in JSON, rather than just plain text for humans. This would allow it to be more easily integrated into linting orchestration tools such as arcanist.

**Comment by schorfES** [comment]
Hi @mwgamble, I think an additional option would be nice. Until then, you might take a look at [lintspaces](https://github.com/schorfES/node-lintspaces) itself to get this output.

**Comment by evanshortiss** [comment]
@mwgamble I'd be in favour of this option, could be simple as having `--json` arg. If you can PR that'd be awesome. After Christmas I could look into it.

**Comment by evanshortiss** [comment]
Just looked at this over lunch. It's simple. I'll publish it today or tomorrow

**Comment by evanshortiss** [comment]
@mwgamble published as version 0.7.0
