### ISSUE TITLE
Cannot pass regex into ignores

### ISSUE THREAD

**Issue by matthew-andrews** [evanshortiss/lintspaces-cli#3]
Firstly - great module it's helped us catch all sorts of subtle mistakes. :smile:

It would be super handy if you could pass regular expressions in as custom ignores.

- Would need to convert from string to `RegExp` object at some point
- `list` would need to be enhanced so it didn't split on a comma in the middle of a regex.

I'm not sure myself if supporting this is even a good idea - I tried implemented it and it's non-trivial.

I was testing with the following command:-
```
lintspaces test.js -d tabs -i '"/var ([^=]+=.*,)*([^=]+=.*;)/g",js-comments'
```

**Comment by kaelig** [comment]
Hi @evanshortiss, any chance this will ever get fixed?

**Comment by evanshortiss** [comment]
Hey @kaelig, 

I missed your previous comment, I'll try look into it this week. If you have experimented with a fix I'd be happy to accept a PR

**Comment by evanshortiss** [comment]
@matthew-andrews @kaelig I've taken a look into this have implemented a solution. Can you guys let me know is it workable for you?

The readme for 0.3.0 has the details, but basically this is the new syntax:

```
# -r is for regex ignores, and -i is for built in ignore patterns
lintspaces -r '/pointless|regex/g' -i 'js-comments'
```

**Comment by evanshortiss** [comment]
@matthew-andrews @kaelig closing this now. Let me know if you feel it is not sufficient 😄
