### ISSUE TITLE
Update to latests version of node-lintspaces

### ISSUE THREAD

**Issue by schorfES** [evanshortiss/lintspaces-cli#9]
Hi @evanshortiss,

according to a new option (https://github.com/schorfES/node-lintspaces/pull/34) please update to the latest release of lintspaces@0.8.0.

Thanks in advance!

**Comment by evanshortiss** [comment]
@schorfES on it

**Comment by evanshortiss** [comment]
@schorfES, looks like 0.8.0 is not yet in npm. When do you plan to publish?

**Comment by evanshortiss** [comment]
@schorfES nevermind, I see it is 05.0 for lintspaces, and 0.8.0 for the grunt plugin! 😄

**Comment by evanshortiss** [comment]
@schorfES lintspaces-cli@0.2.0 published 👍

**Comment by schorfES** [comment]
@evanshortiss cool! Thank you!
